name: "Build documentation, check links, spelling, grammar, and style"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

defaults:
  run:
    working-directory: backend

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: false

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}
            uv-${{ runner.os }}-${{ inputs.python-version }}

      - name: Install requirements
        run: |
          cd docs && make install

      - name: Check for broken links
        run: |
          cd docs && make linkcheckbroken

      - name: Build HTML documentation
        run: |
          cd docs && make html

      - name: Run vale
        run: |
          cd docs && make vale VALEOPTS="--minAlertLevel='warning'"
